version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: Docker/Nginx.Dockerfile
    image: nginx
    volumes:
#      - ./:/var/www/herdWatch/herdWatchTest/
      - /var/www/herdWatch/herdWatchTest/:/var/www/app
      - /var/www/herdWatch/herdWatchTestCLI/:/var/www/cli
    ports:
      - 127.0.0.1:8080:80
    links:
      - fpm
      - database
    restart: unless-stopped
    networks:
      - internal
    environment:
      APP_DEBUG: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "herdwatchapi:127.0.0.1"
      - "herdwatchcli:127.0.0.1"
  fpm:
    build:
      context: .
      dockerfile: Docker/Fpm.Dockerfile
    volumes:
#      - ./:/var/www/herdWatch/herdWatchTest/
      - /var/www/herdWatch/herdWatchTest/:/var/www/app
      - /var/www/herdWatch/herdWatchTestCLI/:/var/www/cli
    ports:
      - 127.0.0.1:9000:9000
    links:
      - database
    networks:
      - internal
  database:
    image: mysql:5.6
    restart: always
    container_name: databaseHerdWatch
    volumes:
      - ./tmp/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=4as6iKILL47<>and2002alex
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=databaseHerdWatch
    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.220.0/28
